### ISSUE TITLE
Create Class diagram

### ISSUE THREAD

**Issue by LunarrPhase** [LunarrPhase/Staff-Relations-Managment#43]
For logical view

**Comment by kelly-wald** [comment]
https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=ClassDiagram.drawio#R7Vxtc9o4EP41zOQ%2BkPEbBn8MkLTXS9q05JreRwUr4IuxqCwC9NdXsiXbkg0xNBZpx53OgNbyaiU9633WK9KxR4vNOwyW8xvkw7BjGf6mY487lmV6nkE%2FmGTLJYbbTyUzHPhclgsmwQ8oOnLpKvBhLHUkCIUkWMrCKYoiOCWSDGCM1nK3RxTKoy7BDJYEkykIy9L7wCfzVDqw%2Brn8PQxmczGy6XrplQUQnflM4jnw0bogsi879ggjRNJvi80Ihmz1xLrc%2F729D6%2Bf3HcfPsffwb%2FDf%2B4%2Bfu2myq4OuSWbAoYROVo1CcKbFf7w6fbushuEn8NvT9b%2FXYcvwzMIV3zBOpYb0lGGSzZlsuXr6H5fsXkOFwDPgqhjXxjLTdbsErSkIicREbghXRAGM9ZrSi2GmEpzDfTbjH8m4zwIwfsvQkQn8aB2o7KlKptjZqOAnBjALI5VMYUHhH2Iu%2FzCRYxCtkR7LDxkJUL4SLKlKKvsUlVXAY7JR7Bgg9PmhOAgmu2b5iuPP1nh6HSjXy5AEJ5o7FsQx2u6%2B3WH%2F%2F3w1bGYTTOY4Ovsr3Sisc51Ti2IuQU50FIjuEXPiC6JTnvoiiTAO%2B2SpCZA7gGnWpFuaoxwhrNl7hWn3aQbCMJPSxKgKBb7xH20N%2Bz0xtpssamyEYaAwMtnGr%2FOCnZJ6OFWjVh3gO9BPE8vDym%2FgSBKr4ypmlTs0298WolenY%2F8OVpfQeg%2FgOnT2QRGPovJiSGLZYi2UNjF%2BgxpH21LzSkArhPt24E1DGxJQ1rPEJOAkumLlM%2BNE6I35OxunI45RLTXY5hQ48eAck4aOMmCfoxN%2BnU9DwicLMGUaVzTJCMbhumGItGoSXHNjHfTjAWiBSR4S%2B%2FjWnqcqfNcpc%2Bb65z3OyItmRc4v2VzIeC5xizTnPNp%2BoVT6gPotTDoLdBr4eotyW5Jdkuyf52t0Cj%2FlPIDmETzPLDzYPpVN3%2BipO4uWMDJHEJy5ku8I%2BUiJJDZeJHB0C17qmDqmUKtMxE85KwWL%2FmtY5bdl4OWbXulqGV7FVHLdN2mopZVilqcsCorHa%2BDRQgi2ho%2BoohM%2BBWDtqfzIPSvwRatmLkxoZsnWsM5wsEP2h%2BI9aaXMeGvDi2XaaNbMkIhoqFtHKFkgPymCVPGh8GQPTluxRaYiugGbKSO1yAmwkAUhmAZBw%2BJyWYG0CEiBC14pyogFHDSFCZMQ8FEBZMxnSpMGE5TmLArmAxz1UWWHFU9WRTAMPKS7DdGT1DZ4Io9V3y22rFjuj10xOukz9jJJV%2F4ujiyu88D34cRgwQigICHDLJLFEQkWTdm%2FJAu78g47%2FEHZI9FJNGm%2F1l3TEY0JSQYBMleQwquNWQAexXc7HHNMnA4UCy3Hk6sxh4dzg6YSAnyg0iQW3hohYd4sJ8OHr0d8MjZSvK%2BpAWGXmD0B6cGhlcBDAUEMPIvWEGQttAy2QkquUrIW7I6tMU5hGnJ64bRKvKhz%2FeLrhTefmMNuiu8%2BV%2Fx2ngjtbaitQlIepvlmbyd3HfuDQa8nd%2FKGsU7byGmVDrJ1hNZOj3ol6qXdZgDXRe0wlO4Z0VFZY9Sqxk8BhpFLLgcCxiGgATPsslVYODqbplrFHiNqfAaS3nxks6K31WsZSqKLJU0q4rSWZcUJdjM5ng8XMV6FOCapygtSdZCkh0FA32vgiS7Wkmya5Zgwd6IfIFTSJ1GeeXeBrnXDnKuUQ2YPeS4Ch%2BNBTm3nFcnrwor6jEtODSDo4oa6wXHrgRb1O3kwnULD63wqCLIeuFRlVifqJJ0AyIwg7gtJLWFpLaQ1BaS%2FpxCUhNGpA9LXxC77GRTxvT2nG36owpbPbucn2kubLnl148FWLZ5u5a8XT2k4zhlajWogkVjp3QE3krUexWX87KrjP20FPyVKXjv4PS9CifNUfCq30q0xYuTA6MqddcLjMEOYOyiSS1AtAKkKnnXCpD%2BnicHaN%2FrnBAaWS3gdNioeng0X%2FnsH1f67EhlT%2FftlT17O97jNVDNtJVqpuPa5z1ZSd16pmn1qknxC%2FVMigqwLXTjHrm7AKuM0zOk34zSL6nGVy2W9k9T2x%2F03SLEu8a5YZsv4Zy1VMgK8DMNhit5gGnbb84DxJviFwv%2Fux6NTRT%2BlQONrprL1S78uy8oeiVHsYyB7CicZDbqKCLuaHEUDmqzhOneEU%2F1zO2oOtNT3M42Bse4nZ5IUcdPbG1%2Bkp1hECHlWD9xB8pbln4zfjIwVIPtvXap%2FcVLwbr9B66GgDUoH%2BPQEbAcmiYoAcuw6xKzc8fxCm7M3PpIN3678UoftVPPFmXudLAf2i8oavig2sDSH1LkJCFNNHbDMIscUj5y3jedtxg0aoM1PQh%2FmjzkWLBaA%2FVh3qsF1oPJlTKOy4%2BF17bL0REEqs7jNB8EPM%2BVHcHse8c4gpS0WJJHWp51cGR4M2RM42nlV%2FMrNZqUFDUdBKrODu2Gsh%2BABYr8u3kgI9qQEG05NRHt9voyoj3v19NwW0K065pvDtHisOeLiE4P6utBtKWwaefYSKGk4XafbUrhn1sL4IcGjpL9%2FGcjRwYC2sz%2FelvaPf8jePblTw%3D%3D
